// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brands.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (slug, name, slogan, logo_url, theme)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, slogan, logo_url, theme, is_active, created_at, updated_at
`

type CreateBrandParams struct {
	Slug    string  `json:"slug"`
	Name    string  `json:"name"`
	Slogan  *string `json:"slogan"`
	LogoUrl *string `json:"logoUrl"`
	Theme   []byte  `json:"theme"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand,
		arg.Slug,
		arg.Name,
		arg.Slogan,
		arg.LogoUrl,
		arg.Theme,
	)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Slogan,
		&i.LogoUrl,
		&i.Theme,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStore = `-- name: CreateStore :one
INSERT INTO stores (brand_id, code, name, address, phone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, brand_id, code, name, address, phone, timezone, is_active, created_at, updated_at, bank_bin, bank_code, bank_account, bank_holder, next_order_no
`

type CreateStoreParams struct {
	BrandID uuid.UUID `json:"brandId"`
	Code    string    `json:"code"`
	Name    string    `json:"name"`
	Address *string   `json:"address"`
	Phone   *string   `json:"phone"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.BrandID,
		arg.Code,
		arg.Name,
		arg.Address,
		arg.Phone,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankBin,
		&i.BankCode,
		&i.BankAccount,
		&i.BankHolder,
		&i.NextOrderNo,
	)
	return i, err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, slug, name, slogan, logo_url, theme, is_active, created_at, updated_at FROM brands WHERE id = $1
`

func (q *Queries) GetBrandByID(ctx context.Context, id uuid.UUID) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Slogan,
		&i.LogoUrl,
		&i.Theme,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandBySlug = `-- name: GetBrandBySlug :one
SELECT id, slug, name, slogan, logo_url, theme, is_active, created_at, updated_at FROM brands WHERE slug = $1
`

func (q *Queries) GetBrandBySlug(ctx context.Context, slug string) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandBySlug, slug)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Slogan,
		&i.LogoUrl,
		&i.Theme,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandStats = `-- name: GetBrandStats :one
SELECT
  (SELECT count(*) FROM stores s          WHERE s.brand_id = $1 AND s.is_active)::bigint    AS stores,
  (SELECT count(*) FROM users u           WHERE u.brand_id = $1 AND u.is_active)::bigint    AS users,
  (SELECT count(*) FROM menu_categories c WHERE c.brand_id = $1 AND c.is_active)::bigint    AS categories,
  (SELECT count(*) FROM menu_items i      WHERE i.brand_id = $1)::bigint                    AS items,
  (SELECT count(*) FROM menu_items i      WHERE i.brand_id = $1 AND i.is_available)::bigint AS available_items
`

type GetBrandStatsRow struct {
	Stores         int64 `json:"stores"`
	Users          int64 `json:"users"`
	Categories     int64 `json:"categories"`
	Items          int64 `json:"items"`
	AvailableItems int64 `json:"availableItems"`
}

func (q *Queries) GetBrandStats(ctx context.Context, brandID uuid.UUID) (GetBrandStatsRow, error) {
	row := q.db.QueryRow(ctx, getBrandStats, brandID)
	var i GetBrandStatsRow
	err := row.Scan(
		&i.Stores,
		&i.Users,
		&i.Categories,
		&i.Items,
		&i.AvailableItems,
	)
	return i, err
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, brand_id, code, name, address, phone, timezone, is_active, created_at, updated_at, bank_bin, bank_code, bank_account, bank_holder, next_order_no FROM stores WHERE id = $1
`

func (q *Queries) GetStoreByID(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankBin,
		&i.BankCode,
		&i.BankAccount,
		&i.BankHolder,
		&i.NextOrderNo,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, slug, name, slogan, logo_url, theme, is_active, created_at, updated_at FROM brands ORDER BY created_at
`

func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Slogan,
			&i.LogoUrl,
			&i.Theme,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoresByBrand = `-- name: ListStoresByBrand :many
SELECT id, brand_id, code, name, address, phone, timezone, is_active, created_at, updated_at, bank_bin, bank_code, bank_account, bank_holder, next_order_no FROM stores WHERE brand_id = $1 ORDER BY created_at
`

func (q *Queries) ListStoresByBrand(ctx context.Context, brandID uuid.UUID) ([]Store, error) {
	rows, err := q.db.Query(ctx, listStoresByBrand, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Code,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BankBin,
			&i.BankCode,
			&i.BankAccount,
			&i.BankHolder,
			&i.NextOrderNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderNo = `-- name: NextOrderNo :one
UPDATE stores SET next_order_no = next_order_no + 1
WHERE id = $1
RETURNING (next_order_no - 1)::integer AS order_no
`

func (q *Queries) NextOrderNo(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextOrderNo, id)
	var order_no int32
	err := row.Scan(&order_no)
	return order_no, err
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE brands
SET name = $2, slogan = $3, logo_url = $4, theme = $5, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, slogan, logo_url, theme, is_active, created_at, updated_at
`

type UpdateBrandParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Slogan  *string   `json:"slogan"`
	LogoUrl *string   `json:"logoUrl"`
	Theme   []byte    `json:"theme"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, updateBrand,
		arg.ID,
		arg.Name,
		arg.Slogan,
		arg.LogoUrl,
		arg.Theme,
	)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Slogan,
		&i.LogoUrl,
		&i.Theme,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStoreBank = `-- name: UpdateStoreBank :one
UPDATE stores
SET bank_bin = $2, bank_code = $3, bank_account = $4, bank_holder = $5, updated_at = now()
WHERE id = $1
RETURNING id, brand_id, code, name, address, phone, timezone, is_active, created_at, updated_at, bank_bin, bank_code, bank_account, bank_holder, next_order_no
`

type UpdateStoreBankParams struct {
	ID          uuid.UUID `json:"id"`
	BankBin     *string   `json:"bankBin"`
	BankCode    *string   `json:"bankCode"`
	BankAccount *string   `json:"bankAccount"`
	BankHolder  *string   `json:"bankHolder"`
}

func (q *Queries) UpdateStoreBank(ctx context.Context, arg UpdateStoreBankParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreBank,
		arg.ID,
		arg.BankBin,
		arg.BankCode,
		arg.BankAccount,
		arg.BankHolder,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankBin,
		&i.BankCode,
		&i.BankAccount,
		&i.BankHolder,
		&i.NextOrderNo,
	)
	return i, err
}
