// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addCustomerPoints = `-- name: AddCustomerPoints :one
UPDATE customers SET points = points + $3, updated_at = now()
WHERE id = $1 AND brand_id = $2
RETURNING id, brand_id, phone, name, points, created_at, updated_at
`

type AddCustomerPointsParams struct {
	ID      uuid.UUID `json:"id"`
	BrandID uuid.UUID `json:"brandId"`
	Points  int32     `json:"points"`
}

func (q *Queries) AddCustomerPoints(ctx context.Context, arg AddCustomerPointsParams) (Customer, error) {
	row := q.db.QueryRow(ctx, addCustomerPoints, arg.ID, arg.BrandID, arg.Points)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Phone,
		&i.Name,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (brand_id, phone, name, points)
VALUES ($1, $2, $3, $4)
RETURNING id, brand_id, phone, name, points, created_at, updated_at
`

type CreateCustomerParams struct {
	BrandID uuid.UUID `json:"brandId"`
	Phone   string    `json:"phone"`
	Name    string    `json:"name"`
	Points  int32     `json:"points"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.BrandID,
		arg.Phone,
		arg.Name,
		arg.Points,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Phone,
		&i.Name,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, brand_id, phone, name, points, created_at, updated_at FROM customers WHERE id = $1 AND brand_id = $2
`

type GetCustomerByIDParams struct {
	ID      uuid.UUID `json:"id"`
	BrandID uuid.UUID `json:"brandId"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.BrandID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Phone,
		&i.Name,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, brand_id, phone, name, points, created_at, updated_at FROM customers WHERE brand_id = $1 AND phone = $2
`

type GetCustomerByPhoneParams struct {
	BrandID uuid.UUID `json:"brandId"`
	Phone   string    `json:"phone"`
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, arg.BrandID, arg.Phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Phone,
		&i.Name,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
