// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO menu_categories (brand_id, name, sort_order)
VALUES ($1, $2, $3)
RETURNING id, brand_id, name, sort_order, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	BrandID   uuid.UUID `json:"brandId"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sortOrder"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.BrandID, arg.Name, arg.SortOrder)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO menu_items (brand_id, category_id, name, description, image_url, base_price, options, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, brand_id, category_id, name, description, image_url, base_price, options, is_available, sort_order, created_at, updated_at
`

type CreateItemParams struct {
	BrandID     uuid.UUID `json:"brandId"`
	CategoryID  uuid.UUID `json:"categoryId"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ImageUrl    *string   `json:"imageUrl"`
	BasePrice   int64     `json:"basePrice"`
	Options     []byte    `json:"options"`
	SortOrder   int32     `json:"sortOrder"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.BrandID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.BasePrice,
		arg.Options,
		arg.SortOrder,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.BasePrice,
		&i.Options,
		&i.IsAvailable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, brand_id, category_id, name, description, image_url, base_price, options, is_available, sort_order, created_at, updated_at FROM menu_items
WHERE id = $1 AND brand_id = $2
`

type GetItemByIDParams struct {
	ID      uuid.UUID `json:"id"`
	BrandID uuid.UUID `json:"brandId"`
}

func (q *Queries) GetItemByID(ctx context.Context, arg GetItemByIDParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getItemByID, arg.ID, arg.BrandID)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.BasePrice,
		&i.Options,
		&i.IsAvailable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByBrand = `-- name: ListCategoriesByBrand :many
SELECT id, brand_id, name, sort_order, is_active, created_at, updated_at FROM menu_categories
WHERE brand_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListCategoriesByBrand(ctx context.Context, brandID uuid.UUID) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesByBrand, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuCategory
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByStore = `-- name: ListCategoriesByStore :many
SELECT c.id, c.brand_id, c.name, c.sort_order, c.is_active, c.created_at, c.updated_at
FROM menu_categories c
JOIN stores s ON s.brand_id = c.brand_id
WHERE s.id = $1 AND c.is_active
ORDER BY c.sort_order, c.name
`

func (q *Queries) ListCategoriesByStore(ctx context.Context, id uuid.UUID) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesByStore, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuCategory
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByBrand = `-- name: ListItemsByBrand :many
SELECT id, brand_id, category_id, name, description, image_url, base_price, options, is_available, sort_order, created_at, updated_at FROM menu_items
WHERE brand_id = $1
ORDER BY category_id, sort_order, name
`

func (q *Queries) ListItemsByBrand(ctx context.Context, brandID uuid.UUID) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listItemsByBrand, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.BasePrice,
			&i.Options,
			&i.IsAvailable,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreMenu = `-- name: ListStoreMenu :many
SELECT i.id, i.brand_id, i.category_id, i.name, i.description, i.image_url, i.base_price, i.options, i.is_available, i.sort_order, i.created_at, i.updated_at,
       COALESCE(o.price_override, i.base_price)::bigint          AS price,
       (i.is_available AND COALESCE(o.is_available, true))::boolean AS store_available
FROM menu_items i
JOIN stores s ON s.id = $1 AND s.brand_id = i.brand_id
LEFT JOIN store_menu_items o ON o.item_id = i.id AND o.store_id = s.id
ORDER BY i.category_id, i.sort_order, i.name
`

type ListStoreMenuRow struct {
	ID             uuid.UUID `json:"id"`
	BrandID        uuid.UUID `json:"brandId"`
	CategoryID     uuid.UUID `json:"categoryId"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	ImageUrl       *string   `json:"imageUrl"`
	BasePrice      int64     `json:"basePrice"`
	Options        []byte    `json:"options"`
	IsAvailable    bool      `json:"isAvailable"`
	SortOrder      int32     `json:"sortOrder"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
	Price          int64     `json:"price"`
	StoreAvailable bool      `json:"storeAvailable"`
}

func (q *Queries) ListStoreMenu(ctx context.Context, id uuid.UUID) ([]ListStoreMenuRow, error) {
	rows, err := q.db.Query(ctx, listStoreMenu, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoreMenuRow
	for rows.Next() {
		var i ListStoreMenuRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.BasePrice,
			&i.Options,
			&i.IsAvailable,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Price,
			&i.StoreAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItemAvailability = `-- name: SetItemAvailability :one
UPDATE menu_items
SET is_available = $3, updated_at = now()
WHERE id = $1 AND brand_id = $2
RETURNING id, brand_id, category_id, name, description, image_url, base_price, options, is_available, sort_order, created_at, updated_at
`

type SetItemAvailabilityParams struct {
	ID          uuid.UUID `json:"id"`
	BrandID     uuid.UUID `json:"brandId"`
	IsAvailable bool      `json:"isAvailable"`
}

func (q *Queries) SetItemAvailability(ctx context.Context, arg SetItemAvailabilityParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, setItemAvailability, arg.ID, arg.BrandID, arg.IsAvailable)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.BasePrice,
		&i.Options,
		&i.IsAvailable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE menu_categories
SET name = $3, sort_order = $4, is_active = $5, updated_at = now()
WHERE id = $1 AND brand_id = $2
RETURNING id, brand_id, name, sort_order, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID        uuid.UUID `json:"id"`
	BrandID   uuid.UUID `json:"brandId"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sortOrder"`
	IsActive  bool      `json:"isActive"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.BrandID,
		arg.Name,
		arg.SortOrder,
		arg.IsActive,
	)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE menu_items
SET category_id = $3, name = $4, description = $5, image_url = $6,
    base_price = $7, options = $8, sort_order = $9, updated_at = now()
WHERE id = $1 AND brand_id = $2
RETURNING id, brand_id, category_id, name, description, image_url, base_price, options, is_available, sort_order, created_at, updated_at
`

type UpdateItemParams struct {
	ID          uuid.UUID `json:"id"`
	BrandID     uuid.UUID `json:"brandId"`
	CategoryID  uuid.UUID `json:"categoryId"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ImageUrl    *string   `json:"imageUrl"`
	BasePrice   int64     `json:"basePrice"`
	Options     []byte    `json:"options"`
	SortOrder   int32     `json:"sortOrder"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.BrandID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.BasePrice,
		arg.Options,
		arg.SortOrder,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.BasePrice,
		&i.Options,
		&i.IsAvailable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
