// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Brand struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	Slogan    *string   `json:"slogan"`
	LogoUrl   *string   `json:"logoUrl"`
	Theme     []byte    `json:"theme"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Customer struct {
	ID        uuid.UUID `json:"id"`
	BrandID   uuid.UUID `json:"brandId"`
	Phone     string    `json:"phone"`
	Name      string    `json:"name"`
	Points    int32     `json:"points"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type MenuCategory struct {
	ID        uuid.UUID `json:"id"`
	BrandID   uuid.UUID `json:"brandId"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sortOrder"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type MenuItem struct {
	ID          uuid.UUID `json:"id"`
	BrandID     uuid.UUID `json:"brandId"`
	CategoryID  uuid.UUID `json:"categoryId"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ImageUrl    *string   `json:"imageUrl"`
	BasePrice   int64     `json:"basePrice"`
	Options     []byte    `json:"options"`
	IsAvailable bool      `json:"isAvailable"`
	SortOrder   int32     `json:"sortOrder"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Order struct {
	ID            uuid.UUID  `json:"id"`
	BrandID       uuid.UUID  `json:"brandId"`
	StoreID       uuid.UUID  `json:"storeId"`
	OrderNo       int32      `json:"orderNo"`
	Number        string     `json:"number"`
	Source        string     `json:"source"`
	OrderType     string     `json:"orderType"`
	TableLabel    *string    `json:"tableLabel"`
	Status        string     `json:"status"`
	PaymentStatus string     `json:"paymentStatus"`
	PaymentMethod *string    `json:"paymentMethod"`
	CashReceived  *int64     `json:"cashReceived"`
	ChangeDue     *int64     `json:"changeDue"`
	CustomerID    *uuid.UUID `json:"customerId"`
	CustomerName  *string    `json:"customerName"`
	CustomerPhone *string    `json:"customerPhone"`
	PromotionCode *string    `json:"promotionCode"`
	Subtotal      int64      `json:"subtotal"`
	Discount      int64      `json:"discount"`
	Total         int64      `json:"total"`
	PointsEarned  int32      `json:"pointsEarned"`
	Note          *string    `json:"note"`
	CreatedBy     *uuid.UUID `json:"createdBy"`
	PaidAt        *time.Time `json:"paidAt"`
	CreatedAt     time.Time  `json:"createdAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
	TableID       *uuid.UUID `json:"tableId"`
}

type OrderItem struct {
	ID          uuid.UUID  `json:"id"`
	OrderID     uuid.UUID  `json:"orderId"`
	ItemID      *uuid.UUID `json:"itemId"`
	Name        string     `json:"name"`
	Quantity    int32      `json:"quantity"`
	UnitPrice   int64      `json:"unitPrice"`
	LineTotal   int64      `json:"lineTotal"`
	Choices     []byte     `json:"choices"`
	OptionsText string     `json:"optionsText"`
	Note        *string    `json:"note"`
	SortOrder   int32      `json:"sortOrder"`
}

type Promotion struct {
	ID          uuid.UUID `json:"id"`
	BrandID     uuid.UUID `json:"brandId"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Type        string    `json:"type"`
	Value       int64     `json:"value"`
	MinSubtotal int64     `json:"minSubtotal"`
	IsActive    bool      `json:"isActive"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Role struct {
	Code  string `json:"code"`
	Name  string `json:"name"`
	Level int16  `json:"level"`
}

type Store struct {
	ID          uuid.UUID `json:"id"`
	BrandID     uuid.UUID `json:"brandId"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Address     *string   `json:"address"`
	Phone       *string   `json:"phone"`
	Timezone    string    `json:"timezone"`
	IsActive    bool      `json:"isActive"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	BankBin     *string   `json:"bankBin"`
	BankCode    *string   `json:"bankCode"`
	BankAccount *string   `json:"bankAccount"`
	BankHolder  *string   `json:"bankHolder"`
	NextOrderNo int32     `json:"nextOrderNo"`
}

type StoreMenuItem struct {
	StoreID       uuid.UUID `json:"storeId"`
	ItemID        uuid.UUID `json:"itemId"`
	PriceOverride *int64    `json:"priceOverride"`
	IsAvailable   bool      `json:"isAvailable"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type StoreTable struct {
	ID        uuid.UUID `json:"id"`
	StoreID   uuid.UUID `json:"storeId"`
	Name      string    `json:"name"`
	Zone      string    `json:"zone"`
	Seats     int16     `json:"seats"`
	SortOrder int32     `json:"sortOrder"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	BrandID      *uuid.UUID `json:"brandId"`
	StoreID      *uuid.UUID `json:"storeId"`
	RoleCode     string     `json:"roleCode"`
	Email        *string    `json:"email"`
	Phone        *string    `json:"phone"`
	FullName     string     `json:"fullName"`
	PasswordHash *string    `json:"passwordHash"`
	IsActive     bool       `json:"isActive"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	PinHash      *string    `json:"pinHash"`
	AvatarUrl    *string    `json:"avatarUrl"`
}
