// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Brand struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	Slogan    *string   `json:"slogan"`
	LogoUrl   *string   `json:"logoUrl"`
	Theme     []byte    `json:"theme"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type MenuCategory struct {
	ID        uuid.UUID `json:"id"`
	BrandID   uuid.UUID `json:"brandId"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sortOrder"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type MenuItem struct {
	ID          uuid.UUID `json:"id"`
	BrandID     uuid.UUID `json:"brandId"`
	CategoryID  uuid.UUID `json:"categoryId"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ImageUrl    *string   `json:"imageUrl"`
	BasePrice   int64     `json:"basePrice"`
	Options     []byte    `json:"options"`
	IsAvailable bool      `json:"isAvailable"`
	SortOrder   int32     `json:"sortOrder"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Role struct {
	Code  string `json:"code"`
	Name  string `json:"name"`
	Level int16  `json:"level"`
}

type Store struct {
	ID        uuid.UUID `json:"id"`
	BrandID   uuid.UUID `json:"brandId"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Address   *string   `json:"address"`
	Phone     *string   `json:"phone"`
	Timezone  string    `json:"timezone"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type StoreMenuItem struct {
	StoreID       uuid.UUID `json:"storeId"`
	ItemID        uuid.UUID `json:"itemId"`
	PriceOverride *int64    `json:"priceOverride"`
	IsAvailable   bool      `json:"isAvailable"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	BrandID      *uuid.UUID `json:"brandId"`
	StoreID      *uuid.UUID `json:"storeId"`
	RoleCode     string     `json:"roleCode"`
	Email        *string    `json:"email"`
	Phone        *string    `json:"phone"`
	FullName     string     `json:"fullName"`
	PasswordHash *string    `json:"passwordHash"`
	IsActive     bool       `json:"isActive"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
}
