// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOrdersByStore = `-- name: CountOrdersByStore :one
SELECT count(*) FROM orders WHERE store_id = $1
`

func (q *Queries) CountOrdersByStore(ctx context.Context, storeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByStore, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    brand_id, store_id, order_no, number, source, order_type, table_label, table_id, status,
    payment_status, payment_method, paid_at,
    customer_id, customer_name, customer_phone, promotion_code,
    subtotal, discount, total, points_earned, note, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19, $20, $21, $22
)
RETURNING id, brand_id, store_id, order_no, number, source, order_type, table_label, status, payment_status, payment_method, cash_received, change_due, customer_id, customer_name, customer_phone, promotion_code, subtotal, discount, total, points_earned, note, created_by, paid_at, created_at, updated_at, table_id
`

type CreateOrderParams struct {
	BrandID       uuid.UUID  `json:"brandId"`
	StoreID       uuid.UUID  `json:"storeId"`
	OrderNo       int32      `json:"orderNo"`
	Number        string     `json:"number"`
	Source        string     `json:"source"`
	OrderType     string     `json:"orderType"`
	TableLabel    *string    `json:"tableLabel"`
	TableID       *uuid.UUID `json:"tableId"`
	Status        string     `json:"status"`
	PaymentStatus string     `json:"paymentStatus"`
	PaymentMethod *string    `json:"paymentMethod"`
	PaidAt        *time.Time `json:"paidAt"`
	CustomerID    *uuid.UUID `json:"customerId"`
	CustomerName  *string    `json:"customerName"`
	CustomerPhone *string    `json:"customerPhone"`
	PromotionCode *string    `json:"promotionCode"`
	Subtotal      int64      `json:"subtotal"`
	Discount      int64      `json:"discount"`
	Total         int64      `json:"total"`
	PointsEarned  int32      `json:"pointsEarned"`
	Note          *string    `json:"note"`
	CreatedBy     *uuid.UUID `json:"createdBy"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.BrandID,
		arg.StoreID,
		arg.OrderNo,
		arg.Number,
		arg.Source,
		arg.OrderType,
		arg.TableLabel,
		arg.TableID,
		arg.Status,
		arg.PaymentStatus,
		arg.PaymentMethod,
		arg.PaidAt,
		arg.CustomerID,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.PromotionCode,
		arg.Subtotal,
		arg.Discount,
		arg.Total,
		arg.PointsEarned,
		arg.Note,
		arg.CreatedBy,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.StoreID,
		&i.OrderNo,
		&i.Number,
		&i.Source,
		&i.OrderType,
		&i.TableLabel,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CashReceived,
		&i.ChangeDue,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.PromotionCode,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.PointsEarned,
		&i.Note,
		&i.CreatedBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, item_id, name, quantity, unit_price, line_total, choices, options_text, note, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, order_id, item_id, name, quantity, unit_price, line_total, choices, options_text, note, sort_order
`

type CreateOrderItemParams struct {
	OrderID     uuid.UUID  `json:"orderId"`
	ItemID      *uuid.UUID `json:"itemId"`
	Name        string     `json:"name"`
	Quantity    int32      `json:"quantity"`
	UnitPrice   int64      `json:"unitPrice"`
	LineTotal   int64      `json:"lineTotal"`
	Choices     []byte     `json:"choices"`
	OptionsText string     `json:"optionsText"`
	Note        *string    `json:"note"`
	SortOrder   int32      `json:"sortOrder"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ItemID,
		arg.Name,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
		arg.Choices,
		arg.OptionsText,
		arg.Note,
		arg.SortOrder,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ItemID,
		&i.Name,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
		&i.Choices,
		&i.OptionsText,
		&i.Note,
		&i.SortOrder,
	)
	return i, err
}

const deleteOrderItems = `-- name: DeleteOrderItems :exec
DELETE FROM order_items WHERE order_id = $1
`

func (q *Queries) DeleteOrderItems(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderItems, orderID)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, brand_id, store_id, order_no, number, source, order_type, table_label, status, payment_status, payment_method, cash_received, change_due, customer_id, customer_name, customer_phone, promotion_code, subtotal, discount, total, points_earned, note, created_by, paid_at, created_at, updated_at, table_id FROM orders WHERE id = $1 AND store_id = $2
`

type GetOrderParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"storeId"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.StoreID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.StoreID,
		&i.OrderNo,
		&i.Number,
		&i.Source,
		&i.OrderType,
		&i.TableLabel,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CashReceived,
		&i.ChangeDue,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.PromotionCode,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.PointsEarned,
		&i.Note,
		&i.CreatedBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, item_id, name, quantity, unit_price, line_total, choices, options_text, note, sort_order FROM order_items
WHERE order_id = ANY($1::uuid[])
ORDER BY order_id, sort_order
`

func (q *Queries) ListOrderItems(ctx context.Context, dollar_1 []uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ItemID,
			&i.Name,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.Choices,
			&i.OptionsText,
			&i.Note,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, brand_id, store_id, order_no, number, source, order_type, table_label, status, payment_status, payment_method, cash_received, change_due, customer_id, customer_name, customer_phone, promotion_code, subtotal, discount, total, points_earned, note, created_by, paid_at, created_at, updated_at, table_id FROM orders
WHERE store_id = $1
  AND created_at >= $2 AND created_at < $3
  AND (cardinality($4::text[]) = 0 OR status = ANY($4::text[]))
  AND (cardinality($5::text[]) = 0 OR source = ANY($5::text[]))
ORDER BY created_at DESC
`

type ListOrdersParams struct {
	StoreID     uuid.UUID `json:"storeId"`
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
	Column4     []string  `json:"column4"`
	Column5     []string  `json:"column5"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.StoreID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.StoreID,
			&i.OrderNo,
			&i.Number,
			&i.Source,
			&i.OrderType,
			&i.TableLabel,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.CashReceived,
			&i.ChangeDue,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.PromotionCode,
			&i.Subtotal,
			&i.Discount,
			&i.Total,
			&i.PointsEarned,
			&i.Note,
			&i.CreatedBy,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TableID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreItemIDs = `-- name: ListStoreItemIDs :many
SELECT i.id, i.name, i.base_price, i.options, i.is_available,
       COALESCE(o.price_override, i.base_price)::bigint          AS price,
       (i.is_available AND COALESCE(o.is_available, true))::boolean AS store_available
FROM menu_items i
JOIN stores s ON s.id = $1 AND s.brand_id = i.brand_id
LEFT JOIN store_menu_items o ON o.item_id = i.id AND o.store_id = s.id
WHERE i.id = ANY($2::uuid[])
`

type ListStoreItemIDsParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 []uuid.UUID `json:"column2"`
}

type ListStoreItemIDsRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	BasePrice      int64     `json:"basePrice"`
	Options        []byte    `json:"options"`
	IsAvailable    bool      `json:"isAvailable"`
	Price          int64     `json:"price"`
	StoreAvailable bool      `json:"storeAvailable"`
}

func (q *Queries) ListStoreItemIDs(ctx context.Context, arg ListStoreItemIDsParams) ([]ListStoreItemIDsRow, error) {
	rows, err := q.db.Query(ctx, listStoreItemIDs, arg.ID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoreItemIDsRow
	for rows.Next() {
		var i ListStoreItemIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BasePrice,
			&i.Options,
			&i.IsAvailable,
			&i.Price,
			&i.StoreAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderSummary = `-- name: OrderSummary :one
SELECT
  count(*) FILTER (WHERE payment_status = 'paid')::bigint                                   AS orders,
  COALESCE(sum(total) FILTER (WHERE payment_status = 'paid'), 0)::bigint                    AS revenue,
  COALESCE(sum(total) FILTER (WHERE payment_status = 'paid' AND payment_method = 'cash'), 0)::bigint    AS cash,
  COALESCE(sum(total) FILTER (WHERE payment_status = 'paid' AND payment_method = 'vietqr'), 0)::bigint  AS vietqr,
  COALESCE(sum(total) FILTER (WHERE payment_status = 'paid' AND payment_method = 'momo'), 0)::bigint    AS momo,
  COALESCE(sum(total) FILTER (WHERE payment_status = 'paid' AND payment_method = 'zalopay'), 0)::bigint AS zalopay,
  count(*) FILTER (WHERE payment_status = 'paid' AND source = 'pos')::bigint                AS pos_orders,
  count(*) FILTER (WHERE payment_status = 'paid' AND source = 'app')::bigint                AS app_orders,
  count(*) FILTER (WHERE status = 'pending')::bigint                                        AS pending_app
FROM orders
WHERE store_id = $1 AND created_at >= $2 AND created_at < $3
`

type OrderSummaryParams struct {
	StoreID     uuid.UUID `json:"storeId"`
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
}

type OrderSummaryRow struct {
	Orders     int64 `json:"orders"`
	Revenue    int64 `json:"revenue"`
	Cash       int64 `json:"cash"`
	Vietqr     int64 `json:"vietqr"`
	Momo       int64 `json:"momo"`
	Zalopay    int64 `json:"zalopay"`
	PosOrders  int64 `json:"posOrders"`
	AppOrders  int64 `json:"appOrders"`
	PendingApp int64 `json:"pendingApp"`
}

func (q *Queries) OrderSummary(ctx context.Context, arg OrderSummaryParams) (OrderSummaryRow, error) {
	row := q.db.QueryRow(ctx, orderSummary, arg.StoreID, arg.CreatedAt, arg.CreatedAt_2)
	var i OrderSummaryRow
	err := row.Scan(
		&i.Orders,
		&i.Revenue,
		&i.Cash,
		&i.Vietqr,
		&i.Momo,
		&i.Zalopay,
		&i.PosOrders,
		&i.AppOrders,
		&i.PendingApp,
	)
	return i, err
}

const payOrder = `-- name: PayOrder :one
UPDATE orders
SET payment_status = 'paid', payment_method = $3, cash_received = $4, change_due = $5,
    paid_at = now(), status = $6, updated_at = now()
WHERE id = $1 AND store_id = $2
RETURNING id, brand_id, store_id, order_no, number, source, order_type, table_label, status, payment_status, payment_method, cash_received, change_due, customer_id, customer_name, customer_phone, promotion_code, subtotal, discount, total, points_earned, note, created_by, paid_at, created_at, updated_at, table_id
`

type PayOrderParams struct {
	ID            uuid.UUID `json:"id"`
	StoreID       uuid.UUID `json:"storeId"`
	PaymentMethod *string   `json:"paymentMethod"`
	CashReceived  *int64    `json:"cashReceived"`
	ChangeDue     *int64    `json:"changeDue"`
	Status        string    `json:"status"`
}

func (q *Queries) PayOrder(ctx context.Context, arg PayOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, payOrder,
		arg.ID,
		arg.StoreID,
		arg.PaymentMethod,
		arg.CashReceived,
		arg.ChangeDue,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.StoreID,
		&i.OrderNo,
		&i.Number,
		&i.Source,
		&i.OrderType,
		&i.TableLabel,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CashReceived,
		&i.ChangeDue,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.PromotionCode,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.PointsEarned,
		&i.Note,
		&i.CreatedBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
	)
	return i, err
}

const replaceOrderHeader = `-- name: ReplaceOrderHeader :one
UPDATE orders
SET order_type = $3, table_label = $4, table_id = $14, customer_id = $5, customer_name = $6, customer_phone = $7,
    promotion_code = $8, subtotal = $9, discount = $10, total = $11, points_earned = $12,
    note = $13, updated_at = now()
WHERE id = $1 AND store_id = $2
RETURNING id, brand_id, store_id, order_no, number, source, order_type, table_label, status, payment_status, payment_method, cash_received, change_due, customer_id, customer_name, customer_phone, promotion_code, subtotal, discount, total, points_earned, note, created_by, paid_at, created_at, updated_at, table_id
`

type ReplaceOrderHeaderParams struct {
	ID            uuid.UUID  `json:"id"`
	StoreID       uuid.UUID  `json:"storeId"`
	OrderType     string     `json:"orderType"`
	TableLabel    *string    `json:"tableLabel"`
	CustomerID    *uuid.UUID `json:"customerId"`
	CustomerName  *string    `json:"customerName"`
	CustomerPhone *string    `json:"customerPhone"`
	PromotionCode *string    `json:"promotionCode"`
	Subtotal      int64      `json:"subtotal"`
	Discount      int64      `json:"discount"`
	Total         int64      `json:"total"`
	PointsEarned  int32      `json:"pointsEarned"`
	Note          *string    `json:"note"`
	TableID       *uuid.UUID `json:"tableId"`
}

func (q *Queries) ReplaceOrderHeader(ctx context.Context, arg ReplaceOrderHeaderParams) (Order, error) {
	row := q.db.QueryRow(ctx, replaceOrderHeader,
		arg.ID,
		arg.StoreID,
		arg.OrderType,
		arg.TableLabel,
		arg.CustomerID,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.PromotionCode,
		arg.Subtotal,
		arg.Discount,
		arg.Total,
		arg.PointsEarned,
		arg.Note,
		arg.TableID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.StoreID,
		&i.OrderNo,
		&i.Number,
		&i.Source,
		&i.OrderType,
		&i.TableLabel,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CashReceived,
		&i.ChangeDue,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.PromotionCode,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.PointsEarned,
		&i.Note,
		&i.CreatedBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
	)
	return i, err
}

const setOrderStatus = `-- name: SetOrderStatus :one
UPDATE orders SET status = $3, updated_at = now()
WHERE id = $1 AND store_id = $2
RETURNING id, brand_id, store_id, order_no, number, source, order_type, table_label, status, payment_status, payment_method, cash_received, change_due, customer_id, customer_name, customer_phone, promotion_code, subtotal, discount, total, points_earned, note, created_by, paid_at, created_at, updated_at, table_id
`

type SetOrderStatusParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"storeId"`
	Status  string    `json:"status"`
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderStatus, arg.ID, arg.StoreID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.StoreID,
		&i.OrderNo,
		&i.Number,
		&i.Source,
		&i.OrderType,
		&i.TableLabel,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CashReceived,
		&i.ChangeDue,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.PromotionCode,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.PointsEarned,
		&i.Note,
		&i.CreatedBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
	)
	return i, err
}

const upsertStoreItemAvailability = `-- name: UpsertStoreItemAvailability :one
INSERT INTO store_menu_items (store_id, item_id, is_available)
VALUES ($1, $2, $3)
ON CONFLICT (store_id, item_id) DO UPDATE
SET is_available = EXCLUDED.is_available, updated_at = now()
RETURNING store_id, item_id, price_override, is_available, updated_at
`

type UpsertStoreItemAvailabilityParams struct {
	StoreID     uuid.UUID `json:"storeId"`
	ItemID      uuid.UUID `json:"itemId"`
	IsAvailable bool      `json:"isAvailable"`
}

func (q *Queries) UpsertStoreItemAvailability(ctx context.Context, arg UpsertStoreItemAvailabilityParams) (StoreMenuItem, error) {
	row := q.db.QueryRow(ctx, upsertStoreItemAvailability, arg.StoreID, arg.ItemID, arg.IsAvailable)
	var i StoreMenuItem
	err := row.Scan(
		&i.StoreID,
		&i.ItemID,
		&i.PriceOverride,
		&i.IsAvailable,
		&i.UpdatedAt,
	)
	return i, err
}
