// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPromotion = `-- name: CreatePromotion :one
INSERT INTO promotions (brand_id, code, name, type, value, min_subtotal)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, brand_id, code, name, type, value, min_subtotal, is_active, created_at, updated_at
`

type CreatePromotionParams struct {
	BrandID     uuid.UUID `json:"brandId"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Type        string    `json:"type"`
	Value       int64     `json:"value"`
	MinSubtotal int64     `json:"minSubtotal"`
}

func (q *Queries) CreatePromotion(ctx context.Context, arg CreatePromotionParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, createPromotion,
		arg.BrandID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Value,
		arg.MinSubtotal,
	)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Value,
		&i.MinSubtotal,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromotionByCode = `-- name: GetPromotionByCode :one
SELECT id, brand_id, code, name, type, value, min_subtotal, is_active, created_at, updated_at FROM promotions
WHERE brand_id = $1 AND upper(code) = upper($2) AND is_active
`

type GetPromotionByCodeParams struct {
	BrandID uuid.UUID   `json:"brandId"`
	Upper   interface{} `json:"upper"`
}

func (q *Queries) GetPromotionByCode(ctx context.Context, arg GetPromotionByCodeParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, getPromotionByCode, arg.BrandID, arg.Upper)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Value,
		&i.MinSubtotal,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
