// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tables.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countStoreTables = `-- name: CountStoreTables :one
SELECT count(*) FROM store_tables WHERE store_id = $1
`

func (q *Queries) CountStoreTables(ctx context.Context, storeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStoreTables, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStoreTable = `-- name: CreateStoreTable :one
INSERT INTO store_tables (store_id, name, zone, seats, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, store_id, name, zone, seats, sort_order, is_active, created_at, updated_at
`

type CreateStoreTableParams struct {
	StoreID   uuid.UUID `json:"storeId"`
	Name      string    `json:"name"`
	Zone      string    `json:"zone"`
	Seats     int16     `json:"seats"`
	SortOrder int32     `json:"sortOrder"`
}

func (q *Queries) CreateStoreTable(ctx context.Context, arg CreateStoreTableParams) (StoreTable, error) {
	row := q.db.QueryRow(ctx, createStoreTable,
		arg.StoreID,
		arg.Name,
		arg.Zone,
		arg.Seats,
		arg.SortOrder,
	)
	var i StoreTable
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Zone,
		&i.Seats,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStoreTable = `-- name: DeleteStoreTable :exec
UPDATE store_tables SET is_active = false, updated_at = now()
WHERE id = $1 AND store_id = $2
`

type DeleteStoreTableParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"storeId"`
}

func (q *Queries) DeleteStoreTable(ctx context.Context, arg DeleteStoreTableParams) error {
	_, err := q.db.Exec(ctx, deleteStoreTable, arg.ID, arg.StoreID)
	return err
}

const getStoreTable = `-- name: GetStoreTable :one
SELECT id, store_id, name, zone, seats, sort_order, is_active, created_at, updated_at FROM store_tables WHERE id = $1 AND store_id = $2
`

type GetStoreTableParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"storeId"`
}

func (q *Queries) GetStoreTable(ctx context.Context, arg GetStoreTableParams) (StoreTable, error) {
	row := q.db.QueryRow(ctx, getStoreTable, arg.ID, arg.StoreID)
	var i StoreTable
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Zone,
		&i.Seats,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnpaidOrderByTable = `-- name: GetUnpaidOrderByTable :one
SELECT id, brand_id, store_id, order_no, number, source, order_type, table_label, status, payment_status, payment_method, cash_received, change_due, customer_id, customer_name, customer_phone, promotion_code, subtotal, discount, total, points_earned, note, created_by, paid_at, created_at, updated_at, table_id FROM orders
WHERE table_id = $1 AND store_id = $2 AND status = 'open'
ORDER BY created_at DESC
LIMIT 1
`

type GetUnpaidOrderByTableParams struct {
	TableID *uuid.UUID `json:"tableId"`
	StoreID uuid.UUID  `json:"storeId"`
}

// The order a table still owes money on, if any. Used to stop a second
// unpaid order being opened on the same table.
func (q *Queries) GetUnpaidOrderByTable(ctx context.Context, arg GetUnpaidOrderByTableParams) (Order, error) {
	row := q.db.QueryRow(ctx, getUnpaidOrderByTable, arg.TableID, arg.StoreID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.StoreID,
		&i.OrderNo,
		&i.Number,
		&i.Source,
		&i.OrderType,
		&i.TableLabel,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CashReceived,
		&i.ChangeDue,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.PromotionCode,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.PointsEarned,
		&i.Note,
		&i.CreatedBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TableID,
	)
	return i, err
}

const listActiveTableOrders = `-- name: ListActiveTableOrders :many
SELECT DISTINCT ON (o.table_id)
       o.table_id, o.id, o.number, o.status, o.payment_status, o.total, o.created_at,
       COALESCE((SELECT sum(oi.quantity) FROM order_items oi WHERE oi.order_id = o.id), 0)::bigint AS item_count
FROM orders o
WHERE o.store_id = $1
  AND o.table_id IS NOT NULL
  AND o.status IN ('open', 'preparing', 'ready')
ORDER BY o.table_id, o.created_at DESC
`

type ListActiveTableOrdersRow struct {
	TableID       *uuid.UUID `json:"tableId"`
	ID            uuid.UUID  `json:"id"`
	Number        string     `json:"number"`
	Status        string     `json:"status"`
	PaymentStatus string     `json:"paymentStatus"`
	Total         int64      `json:"total"`
	CreatedAt     time.Time  `json:"createdAt"`
	ItemCount     int64      `json:"itemCount"`
}

// One row per table that currently has an unfinished order on it. Joined in
// Go rather than with a LEFT JOIN LATERAL so every column stays non-null.
func (q *Queries) ListActiveTableOrders(ctx context.Context, storeID uuid.UUID) ([]ListActiveTableOrdersRow, error) {
	rows, err := q.db.Query(ctx, listActiveTableOrders, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTableOrdersRow
	for rows.Next() {
		var i ListActiveTableOrdersRow
		if err := rows.Scan(
			&i.TableID,
			&i.ID,
			&i.Number,
			&i.Status,
			&i.PaymentStatus,
			&i.Total,
			&i.CreatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreTables = `-- name: ListStoreTables :many
SELECT id, store_id, name, zone, seats, sort_order, is_active, created_at, updated_at FROM store_tables
WHERE store_id = $1 AND is_active
ORDER BY sort_order, name
`

func (q *Queries) ListStoreTables(ctx context.Context, storeID uuid.UUID) ([]StoreTable, error) {
	rows, err := q.db.Query(ctx, listStoreTables, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreTable
	for rows.Next() {
		var i StoreTable
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Zone,
			&i.Seats,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreTable = `-- name: UpdateStoreTable :one
UPDATE store_tables
SET name = $3, zone = $4, seats = $5, sort_order = $6, is_active = $7, updated_at = now()
WHERE id = $1 AND store_id = $2
RETURNING id, store_id, name, zone, seats, sort_order, is_active, created_at, updated_at
`

type UpdateStoreTableParams struct {
	ID        uuid.UUID `json:"id"`
	StoreID   uuid.UUID `json:"storeId"`
	Name      string    `json:"name"`
	Zone      string    `json:"zone"`
	Seats     int16     `json:"seats"`
	SortOrder int32     `json:"sortOrder"`
	IsActive  bool      `json:"isActive"`
}

func (q *Queries) UpdateStoreTable(ctx context.Context, arg UpdateStoreTableParams) (StoreTable, error) {
	row := q.db.QueryRow(ctx, updateStoreTable,
		arg.ID,
		arg.StoreID,
		arg.Name,
		arg.Zone,
		arg.Seats,
		arg.SortOrder,
		arg.IsActive,
	)
	var i StoreTable
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Zone,
		&i.Seats,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
