// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT count(*) FROM users WHERE role_code = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, roleCode string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, roleCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (brand_id, store_id, role_code, email, phone, full_name, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, brand_id, store_id, role_code, email, phone, full_name, password_hash, is_active, created_at, updated_at
`

type CreateUserParams struct {
	BrandID      *uuid.UUID `json:"brandId"`
	StoreID      *uuid.UUID `json:"storeId"`
	RoleCode     string     `json:"roleCode"`
	Email        *string    `json:"email"`
	Phone        *string    `json:"phone"`
	FullName     string     `json:"fullName"`
	PasswordHash *string    `json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.BrandID,
		arg.StoreID,
		arg.RoleCode,
		arg.Email,
		arg.Phone,
		arg.FullName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.StoreID,
		&i.RoleCode,
		&i.Email,
		&i.Phone,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.brand_id, u.store_id, u.role_code, u.email, u.phone, u.full_name, u.password_hash, u.is_active, u.created_at, u.updated_at, r.level AS role_level
FROM users u
JOIN roles r ON r.code = u.role_code
WHERE lower(u.email) = lower($1)
`

type GetUserByEmailRow struct {
	ID           uuid.UUID  `json:"id"`
	BrandID      *uuid.UUID `json:"brandId"`
	StoreID      *uuid.UUID `json:"storeId"`
	RoleCode     string     `json:"roleCode"`
	Email        *string    `json:"email"`
	Phone        *string    `json:"phone"`
	FullName     string     `json:"fullName"`
	PasswordHash *string    `json:"passwordHash"`
	IsActive     bool       `json:"isActive"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	RoleLevel    int16      `json:"roleLevel"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.StoreID,
		&i.RoleCode,
		&i.Email,
		&i.Phone,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleLevel,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.brand_id, u.store_id, u.role_code, u.email, u.phone, u.full_name, u.password_hash, u.is_active, u.created_at, u.updated_at, r.level AS role_level
FROM users u
JOIN roles r ON r.code = u.role_code
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID           uuid.UUID  `json:"id"`
	BrandID      *uuid.UUID `json:"brandId"`
	StoreID      *uuid.UUID `json:"storeId"`
	RoleCode     string     `json:"roleCode"`
	Email        *string    `json:"email"`
	Phone        *string    `json:"phone"`
	FullName     string     `json:"fullName"`
	PasswordHash *string    `json:"passwordHash"`
	IsActive     bool       `json:"isActive"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	RoleLevel    int16      `json:"roleLevel"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.StoreID,
		&i.RoleCode,
		&i.Email,
		&i.Phone,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleLevel,
	)
	return i, err
}

const listUsersByBrand = `-- name: ListUsersByBrand :many
SELECT id, brand_id, store_id, role_code, email, phone, full_name, password_hash, is_active, created_at, updated_at FROM users
WHERE brand_id = $1
ORDER BY created_at
`

func (q *Queries) ListUsersByBrand(ctx context.Context, brandID *uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByBrand, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.StoreID,
			&i.RoleCode,
			&i.Email,
			&i.Phone,
			&i.FullName,
			&i.PasswordHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
